/**
 * GENERATED by docs/calibrate.py from the measurement CSVs. Do not edit by hand.
 *
 * capacity = K * L^a, both per (commodity, level).
 *   non-raws: K = k
 *   raws:     K = base + m * acres, in that raw's own terrain
 */
import type { CommodityId, Level } from "./types.ts";

export interface Params { a: number; k: number }
export interface RawParams { a: number; base: number; m: number }

/** Non-raw productivity, measured per level. */
export const PARAMS: Partial<Record<CommodityId, Partial<Record<Level, Params>>>> = {
  "ball-bearing": {
    expert: { a: 2.2549, k: 0.000578 },
  },
  "cannon": {
    expert: { a: 2.1024, k: 0.000830 },
  },
  "charcoal": {
    beginner: { a: 1.1268, k: 6.489654 },
    intermediate: { a: 1.1262, k: 4.713185 },
    expert: { a: 1.1309, k: 2.904929 },
  },
  "combine": {
    intermediate: { a: 1.7251, k: 0.054967 },
    expert: { a: 1.8055, k: 0.017609 },
  },
  "diesel-engine": {
    expert: { a: 2.5330, k: 0.000093 },
  },
  "electrics": {
    expert: { a: 2.0660, k: 0.002761 },
  },
  "explosives": {
    intermediate: { a: 1.7539, k: 0.033714 },
    expert: { a: 1.7008, k: 0.022135 },
  },
  "farm-tools": {
    beginner: { a: 1.1260, k: 4.716462 },
    intermediate: { a: 1.1295, k: 3.359285 },
    expert: { a: 1.1252, k: 2.170553 },
  },
  "gunpowder": {
    beginner: { a: 1.3817, k: 0.710326 },
    intermediate: { a: 1.3926, k: 0.454693 },
    expert: { a: 1.3981, k: 0.249651 },
  },
  "high-explosives": {
    expert: { a: 2.1493, k: 0.000866 },
  },
  "high-grade-steel": {
    expert: { a: 2.5003, k: 0.000129 },
  },
  "instruments": {
    expert: { a: 2.2188, k: 0.000686 },
  },
  "iron": {
    beginner: { a: 1.6840, k: 0.386694 },
    intermediate: { a: 1.6480, k: 0.288847 },
    expert: { a: 1.7003, k: 0.111240 },
  },
  "iron-plow": {
    beginner: { a: 1.4388, k: 0.420057 },
    intermediate: { a: 1.3868, k: 0.361043 },
    expert: { a: 1.4353, k: 0.158406 },
  },
  "irrigation": {
    expert: { a: 2.0143, k: 0.002656 },
  },
  "low-grade-steel": {
    intermediate: { a: 2.0245, k: 0.034204 },
    expert: { a: 1.8768, k: 0.031288 },
  },
  "musket": {
    beginner: { a: 1.3991, k: 0.571610 },
    intermediate: { a: 1.4152, k: 0.353381 },
    expert: { a: 1.4500, k: 0.166372 },
  },
  "pig-iron": {
    beginner: { a: 1.1260, k: 4.716462 },
    intermediate: { a: 1.1422, k: 3.169069 },
    expert: { a: 1.1252, k: 2.170553 },
  },
  "pipe": {
    expert: { a: 2.0282, k: 0.002853 },
  },
  "rifle": {
    intermediate: { a: 1.7182, k: 0.038465 },
    expert: { a: 1.6730, k: 0.024327 },
  },
  "steam-engine": {
    intermediate: { a: 1.3769, k: 0.303803 },
    expert: { a: 1.6346, k: 0.047541 },
  },
  "sword": {
    beginner: { a: 1.1260, k: 4.716462 },
    intermediate: { a: 1.1295, k: 3.359285 },
    expert: { a: 1.1252, k: 2.170553 },
  },
  "tank": {
    expert: { a: 2.2188, k: 0.000686 },
  },
  "tractor": {
    expert: { a: 2.3531, k: 0.000226 },
  },
  "wire": {
    expert: { a: 2.0250, k: 0.004757 },
  },
};

/**
 * Raw productivity. `base` is the intercept at zero acres of the relevant
 * terrain -- the design dialogue's 'modicum'. Advanced raws have base ~0: no
 * terrain, no output, whatever the labour.
 */
export const RAW_PARAMS: Partial<Record<CommodityId, Partial<Record<Level, RawParams>>>> = {
  "lumber": {
    beginner: { a: 1.1268, base: 6.489669, m: 0.000000 },
    intermediate: { a: 1.1266, base: 2.125067, m: 0.108964 },
    expert: { a: 1.1329, base: 0.717943, m: 0.100671 },
  },
  "sulfur": {
    beginner: { a: 1.6247, base: 0.998894, m: 0.000000 },
    intermediate: { a: 1.7071, base: 0.128931, m: 0.011424 },
    expert: { a: 1.7317, base: 0.010571, m: 0.010582 },
  },
  "iron-ore": {
    beginner: { a: 1.1260, base: 4.716465, m: 0.000000 },
    intermediate: { a: 1.1293, base: 1.537474, m: 0.036977 },
    expert: { a: 1.1396, base: 0.490549, m: 0.034156 },
  },
  "coal": {
    beginner: { a: 1.6910, base: 0.673704, m: 0.000000 },
    intermediate: { a: 1.7284, base: 0.107631, m: 0.005112 },
    expert: { a: 1.7472, base: 0.005168, m: 0.003550 },
  },
  "light-metal": {
    intermediate: { a: 1.9679, base: 0.011088, m: 0.000758 },
    expert: { a: 2.0404, base: 0.000000, m: 0.000364 },
  },
  "nitrate": {
    intermediate: { a: 2.0389, base: 0.005095, m: 0.000781 },
    expert: { a: 2.1471, base: 0.000000, m: 0.000452 },
  },
  "heavy-metal": {
    expert: { a: 2.0208, base: 0.000000, m: 0.000199 },
  },
};
