/**
 * Commodity table and tuning constants, from docs/MECHANICS-SPEC.md.
 *
 * Recipes are §3.3, confirmed in-game. Productivity parameters now come from
 * src/calibration.ts, generated by docs/calibrate.py from 53 raw and 22 intermediate
 * measurements — every commodity is measured, none are placeholders.
 */
import type { Commodity, CommodityId, Level } from "./types.ts";

/**
 * Pig Iron's coefficients disagree between sources (§8.2): the in-game reading is
 * 0.25 charcoal + 0.95 iron ore, but the manual's reference state only closes with
 * ~0.246 + ~0.94. Selectable so the fixture test can report on both.
 */
export type PigIronVariant = "in-game" | "fixture-derived";

/**
 * Default is `fixture-derived`. The in-game display reads 0.25 / 0.95, but those values
 * cannot reproduce the manual's reference state (they give pig iron 196 against an
 * observed 199, and an iron-ore shortfall the screenshot does not show). The screenshot
 * closes on ~0.246 / ~0.94, so the displayed figures are almost certainly rounded.
 */
export const DEFAULT_PIG_IRON: PigIronVariant = "fixture-derived";

const PIG_IRON: Record<PigIronVariant, Record<CommodityId, number>> = {
  "in-game": { charcoal: 0.25, "iron-ore": 0.95 },
  "fixture-derived": { charcoal: 0.246, "iron-ore": 0.94 },
};

export function commodityTable(
  pigIron: PigIronVariant = DEFAULT_PIG_IRON,
): Map<CommodityId, Commodity> {
  const list: Commodity[] = [
    // --- raws (§3.2). Capacity comes from RAW_PARAMS, keyed on `terrain`.
    { id: "lumber", kind: "raw", inputs: {}, terrain: "forest" },
    { id: "sulfur", kind: "raw", inputs: {}, terrain: "desert" },
    { id: "iron-ore", kind: "raw", inputs: {}, terrain: "mountains" },
    { id: "coal", kind: "raw", inputs: {}, terrain: "mountains" },
    { id: "light-metal", kind: "raw", inputs: {}, terrain: "mountains" },
    { id: "nitrate", kind: "raw", inputs: {}, terrain: "desert" },
    { id: "heavy-metal", kind: "raw", inputs: {}, terrain: "mountains" },
    { id: "petroleum", kind: "raw", inputs: {}, terrain: "desert" },

    // --- intermediates
    { id: "charcoal", kind: "intermediate", inputs: { lumber: 1.0 } },
    { id: "pig-iron", kind: "intermediate", inputs: PIG_IRON[pigIron] },
    { id: "gunpowder", kind: "intermediate", inputs: { sulfur: 0.25, charcoal: 0.5 } },
    { id: "iron", kind: "intermediate", inputs: { "iron-ore": 1.0, coal: 0.5 } },
    { id: "low-grade-steel", kind: "intermediate", inputs: { "iron-ore": 0.8, "light-metal": 0.25, coal: 0.8 } },
    { id: "explosives", kind: "intermediate", inputs: { sulfur: 0.25, charcoal: 0.5, nitrate: 0.25 } },
    { id: "high-grade-steel", kind: "intermediate", inputs: { "iron-ore": 0.75, "light-metal": 0.15, coal: 0.75 } },
    { id: "high-explosives", kind: "intermediate", inputs: { sulfur: 0.25, petroleum: 0.5, nitrate: 0.25 } },
    { id: "steam-engine", kind: "intermediate", inputs: { "low-grade-steel": 0.5, coal: 0.5 } },
    { id: "wire", kind: "intermediate", inputs: { "light-metal": 1.0 } },
    { id: "pipe", kind: "intermediate", inputs: { "heavy-metal": 1.0 } },
    { id: "electrics", kind: "intermediate", inputs: { "heavy-metal": 0.5, wire: 0.5 } },
    { id: "ball-bearing", kind: "intermediate", inputs: { "high-grade-steel": 0.6, "heavy-metal": 0.4 } },
    { id: "diesel-engine", kind: "intermediate", inputs: { petroleum: 0.5, "high-grade-steel": 0.4, electrics: 0.1, "ball-bearing": 0.1 } },
    { id: "instruments", kind: "intermediate", inputs: { electrics: 0.5, "ball-bearing": 0.5 } },

    // --- agricultural tiers. Combine precedes Irrigation (§4.3).
    { id: "farm-tools", kind: "tool", tier: 1, inputs: { lumber: 0.5, "pig-iron": 0.5 } },
    { id: "iron-plow", kind: "tool", tier: 2, inputs: { iron: 0.5, lumber: 0.5 } },
    { id: "combine", kind: "tool", tier: 3, inputs: { "steam-engine": 0.5, iron: 0.5 } },
    { id: "irrigation", kind: "tool", tier: 4, inputs: { pipe: 0.75, electrics: 0.25 } },
    { id: "tractor", kind: "tool", tier: 5, inputs: { "diesel-engine": 0.75, "low-grade-steel": 0.25 } },

    // --- weapon tiers
    { id: "sword", kind: "weapon", tier: 1, inputs: { "pig-iron": 1.0 } },
    { id: "musket", kind: "weapon", tier: 2, inputs: { iron: 0.5, gunpowder: 0.5 } },
    { id: "rifle", kind: "weapon", tier: 3, inputs: { "low-grade-steel": 0.5, explosives: 0.5 } },
    { id: "cannon", kind: "weapon", tier: 4, inputs: { "low-grade-steel": 0.5, "high-explosives": 0.5 } },
    { id: "tank", kind: "weapon", tier: 5, inputs: { "high-grade-steel": 0.4, "high-explosives": 0.25, "diesel-engine": 0.25, instruments: 0.125 } },
  ];
  return new Map(list.map((c) => [c.id, c]));
}

/** Tier n yields 2^(n-1), for both food per ton of tool and firepower per ton (§4.3, §5.2). */
export const tierYield = (tier: number): number => 2 ** (tier - 1);

export const PLAYERS: Record<Level, number> = {
  beginner: 2,
  intermediate: 4,
  expert: 8,
};

export const AGRICULTURE = {
  /** Tons of food per acre with no tools (§4.2). */
  baseYield: 1.0,
  /** Tools beyond 1 ton per acre are wasted (§4.2). */
  toolsPerAcre: 1.0,
  /** Workers locked to farmland, not adjustable (§4.1). */
  workersPerAcre: 1.0,
  /** Tons of food per person for break-even (§4.4). */
  foodPerPerson: 1.0,
} as const;

/**
 * Population response to food (§4.4), fitted to 29 readings from the DOS build (§4.4.1).
 *
 *     growth  = growth * surplus / (1 + surplus / (saturation * population))
 *     decline = decline * deficit
 *     floor   = floorPerAcre * farmland        // decline stops here
 *
 * The manual's "square root" turns out not to be how the shipped game behaves: growth is
 * *linear* in surplus, and the diminishing return Crawford wanted — "we can't have them
 * doubling their population merely by doubling their food surplus" — comes from the
 * saturating denominator instead. Doubling a surplus of 0.34 per head multiplies growth
 * by 1.75, not 2.
 *
 * Accuracy against the readings: growth median 4.7%, worst 9.7%; decline median 0.0%,
 * worst 6.6%. `saturation` fitted to 2.02 and is written as measured.
 */
export const POPULATION = {
  growth: 0.4727,
  saturation: 2.0242,
  /**
   * Linear. Every measured deficit is shallow — at most 0.23 per head — and linear fits
   * those to a median of 0.0%. It is taken as linear beyond them too: the saturation in
   * the growth term exists to stop a nation buying unbounded growth with food it cannot
   * otherwise use, and there is no counterpart to that on the way down (§4.4.1).
   */
  decline: 0.6971,
  /**
   * Famine will not take a nation below this multiple of its farmland. Six readings sat
   * exactly here and lost nobody at all, to deficits as deep as 207 tons.
   *
   * The readings cannot tell this apart from "a nation cannot be starved below the
   * population it started with", since a nation starts at exactly this ratio. It is
   * farmland because a turn is a generation and nothing carries over (§3.1.1) — a
   * remembered starting figure would be the one piece of persistent state in the design.
   * So gaining farmland raises a nation's own floor, and taking farmland lowers its
   * victim's.
   */
  floorPerAcre: 1.4933,
} as const;
